version: '3.6'

services:
  mailcatcher.smtp:
    ports:
      - '127.0.0.1:1080:1080'
  diplomacy.service:
    volumes:
      - ./:/opt/diplomacy/diplomacy
    ports:
      - "127.0.0.1:8082:8000"
  diplomacy.worker:
    volumes:
      - ./:/opt/diplomacy/diplomacy
