stp_reps = {
    'St. Petersburg (South Coast)': 'stp_sc',
    'St. Petersburg (North Coast)': 'stp_nc',
    'Bulgaria (South Coast)': 'bul_sc',
    'Bulgaria (East Coast)': 'bul_ec',
    'Spain (South Coast)': 'spa_sc',
    'Spain (North Coast)': 'spa_nc',
}

reps = {
    'Western Mediterranean': 'wes',
    'Edinburgh': 'edi',
    'Eastern Mediterranean': 'eas',
    'Venice': 'ven',
    'North Sea': 'nth',
    'Clyde': 'cly',
    'English Channel': 'eng',
    'Rumania': 'rum',
    'Prussia': 'pru',
    'Irish Sea': 'iri',
    'Brest': 'bre',
    'Budapest': 'bud',
    'Constantinople': 'con',
    'Wales': 'wal',
    'Yorkshire': 'yor',
    'Warsaw': 'war',
    'Berlin': 'ber',
    'Gulf of Lyon': 'gol',
    'Armenia': 'arm',
    'Piedmont': 'pie',
    'Picardy': 'pic',
    'Marseilles': 'mar',
    'Gascony': 'gas',
    'North Atlantic': 'nat',
    'Adriatic Sea': 'adr',
    'Tyrrhenian Sea': 'tyn',
    'Galicia': 'gal',
    'Spain': 'spa',
    'Black Sea': 'bla',
    'Albania': 'alb',
    'Helgoand Bight': 'hel',
    'Norway': 'nwy',
    'Apulia': 'apu',
    'Bulgaria': 'bul',
    'Greece': 'gre',
    'Paris': 'par',
    'Tunis': 'tun',
    'Norwegian Sea': 'nrg',
    'Aegean Sea': 'aeg',
    'Vienna': 'vie',
    'Gulf of Bothnia': 'bot',
    'Smyrna': 'smy',
    'Naples': 'nap',
    'Ukraine': 'ukr',
    'Trieste': 'tri',
    'Finland': 'fin',
    'Serbia': 'ser',
    'London': 'lon',
    'Barrents Sea': 'bar',
    'Silesia': 'sil',
    'St. Petersburg': 'stp',

    'Burgundy': 'bur',
    'Holland': 'hol',
    'Belgium': 'bel',
    'Portugal': 'por',
    'Ionian Sea': 'ion',
    'Denmark': 'den',
    'Munich': 'mun',
    'Ankara': 'ank',
    'Syria': 'syr',
    'Moscow': 'mos',
    'Ruhr': 'ruh',
    'North Africa': 'naf',
    'Kiel': 'kie',
    'Livonia': 'lvn',
    'Bohemia': 'boh',
    'Baltic Sea': 'bal',
    'Liverpool': 'lvp',
    'Tyrolia': 'tyr',
    'Sweden': 'swe',
    'Sevastopol': 'sev',
    'Skagerrack': 'ska',
    'Tuscany': 'tus',
    'Mid-Atlantic Ocean': 'mid',
    'Rome': 'rom',
}