territories = {
    "adr": {
        "display_name": "Adriatic Sea",
        "neighbours": [
            {"name": "alb", "shared_coast": False},
            {"name": "apu", "shared_coast": False},
            {"name": "ion", "shared_coast": False},
            {"name": "tri", "shared_coast": False},
            {"name": "ven", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "aeg": {
        "display_name": "Aegean Sea",
        "neighbours": [
            {"name": "bla", "shared_coast": False},
            {"name": "bul", "shared_coast": False},
            {"name": "con", "shared_coast": False},
            {"name": "eas", "shared_coast": False},
            {"name": "gre", "shared_coast": False},
            {"name": "ion", "shared_coast": False},
            {"name": "smy", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "alb": {
        "display_name": "Albania",
        "neighbours": [
            {"name": "adr", "shared_coast": False},
            {"name": "gre", "shared_coast": True},
            {"name": "ion", "shared_coast": False},
            {"name": "ser", "shared_coast": False},
            {"name": "tri", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "ank": {
        "display_name": "Ankara",
        "nation": "turkey",
        "neighbours": [
            {"name": "arm", "shared_coast": True},
            {"name": "bla", "shared_coast": False},
            {"name": "con", "shared_coast": True},
            {"name": "smy", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "apu": {
        "display_name": "Apulia",
        "neighbours": [
            {"name": "adr", "shared_coast": False},
            {"name": "ion", "shared_coast": False},
            {"name": "nap", "shared_coast": True},
            {"name": "rom", "shared_coast": False},
            {"name": "ven", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "arm": {
        "display_name": "Armenia",
        "nation": "turkey",
        "neighbours": [
            {"name": "ank", "shared_coast": True},
            {"name": "bla", "shared_coast": False},
            {"name": "sev", "shared_coast": True},
            {"name": "smy", "shared_coast": False},
            {"name": "syr", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "bal": {
        "display_name": "Baltic Sea",
        "neighbours": [
            {"name": "ber", "shared_coast": False},
            {"name": "bot", "shared_coast": False},
            {"name": "den", "shared_coast": False},
            {"name": "kie", "shared_coast": False},
            {"name": "pru", "shared_coast": False},
            {"name": "ska", "shared_coast": False},
            {"name": "swe", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "bar": {
        "display_name": "Barrents Sea",
        "neighbours": [
            {"name": "nrg", "shared_coast": False},
            {"name": "nry", "shared_coast": False},
            {"name": "stp", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "ber": {
        "display_name": "Berlin",
        "nation": "germany",
        "neighbours": [
            {"name": "bal", "shared_coast": False},
            {"name": "kie", "shared_coast": True},
            {"name": "mun", "shared_coast": False},
            {"name": "pru", "shared_coast": True},
            {"name": "sil", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "bel": {
        "display_name": "Belgium",
        "neighbours": [
            {"name": "bur", "shared_coast": False},
            {"name": "eng", "shared_coast": False},
            {"name": "hol", "shared_coast": True},
            {"name": "pic", "shared_coast": True},
            {"name": "ruh", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "bla": {
        "display_name": "Black Sea",
        "neighbours": [
            {"name": "ank", "shared_coast": False},
            {"name": "arm", "shared_coast": False},
            {"name": "bul", "shared_coast": False},
            {"name": "con", "shared_coast": False},
            {"name": "rum", "shared_coast": False},
            {"name": "sev", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "boh": {
        "display_name": "Bohemia",
        "neighbours": [
            {"name": "gal", "shared_coast": False},
            {"name": "mun", "shared_coast": False},
            {"name": "sil", "shared_coast": False},
            {"name": "tyr", "shared_coast": False},
            {"name": "vie", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "bot": {
        "display_name": "Gulf of Bothnia",
        "neighbours": [
            {"name": "bal", "shared_coast": False},
            {"name": "fin", "shared_coast": False},
            {"name": "lvn", "shared_coast": False},
            # {"name": "swe", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "bre": {
        "display_name": "Brest",
        "nation": "france",
        "neighbours": [
            {"name": "eng", "shared_coast": False},
            {"name": "gas", "shared_coast": True},
            {"name": "mid", "shared_coast": False},
            {"name": "par", "shared_coast": False},
            {"name": "pic", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "bud": {
        "display_name": "Budapest",
        "nation": "austria",
        "neighbours": [
            {"name": "gal", "shared_coast": False},
            {"name": "rum", "shared_coast": False},
            {"name": "ser", "shared_coast": False},
            {"name": "tri", "shared_coast": False},
            {"name": "vie", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "bul": {
        "display_name": "Bulgaria",
        "neighbours": [
            {"name": "aeg", "shared_coast": False},
            {"name": "bla", "shared_coast": False},
            {"name": "con", "shared_coast": True},
            {"name": "gre", "shared_coast": True},
            {"name": "rum", "shared_coast": True},
            {"name": "ser", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "bur": {
        "display_name": "Burgundy",
        "neighbours": [
            {"name": "bre", "shared_coast": False},
            {"name": "bel", "shared_coast": False},
            {"name": "gas", "shared_coast": False},
            {"name": "mar", "shared_coast": False},
            {"name": "mun", "shared_coast": False},
            {"name": "par", "shared_coast": False},
            {"name": "pic", "shared_coast": False},
            {"name": "ruh", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "cly": {
        "display_name": "Clyde",
        "neighbours": [
            {"name": "edi", "shared_coast": True},
            {"name": "lvp", "shared_coast": True},
            {"name": "iri", "shared_coast": False},
            {"name": "nat", "shared_coast": False},
            {"name": "nrg", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply-center": False,
    },
    "con": {
        "display_name": "Constantinople",
        "nation": "turkey",
        "neighbours": [
            {"name": "aeg", "shared_coast": False},
            {"name": "ank", "shared_coast": True},
            {"name": "bla", "shared_coast": False},
            {"name": "bul", "shared_coast": True},
            {"name": "smy", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "den": {
        "display_name": "Denmark",
        "neighbours": [
            {"name": "bal", "shared_coast": False},
            {"name": "hel", "shared_coast": False},
            {"name": "kie", "shared_coast": True},
            {"name": "nth", "shared_coast": False},
            {"name": "ska", "shared_coast": False},
            {"name": "swe", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "eas": {
        "display_name": "Eastern Mediterranean Sea",
        "neighbours": [
            {"name": "aeg", "shared_coast": False},
            {"name": "smy", "shared_coast": False},
            {"name": "syr", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "edi": {
        "display_name": "Edinburgh",
        "nation": "england",
        "neighbours": [
            {"name": "cly", "shared_coast": True},
            {"name": "lvp", "shared_coast": False},
            {"name": "nth", "shared_coast": False},
            {"name": "yor", "shared_coast": True},
            {"name": "nat", "shared_coast": False},
            {"name": "nrg", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "eng": {
        "display_name": "English Channel",
        "neighbours": [
            {"name": "bel", "shared_coast": False},
            {"name": "bre", "shared_coast": False},
            {"name": "iri", "shared_coast": False},
            {"name": "lon", "shared_coast": False},
            {"name": "mid", "shared_coast": False},
            {"name": "nth", "shared_coast": False},
            {"name": "pic", "shared_coast": False},
            {"name": "wal", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "fin": {
        "display_name": "Finland",
        "neighbours": [
            {"name": "bot", "shared_coast": False},
            {"name": "nwy", "shared_coast": False},
            {"name": "stp", "shared_coast": True},
            {"name": "swe", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "gal": {
        "display_name": "Galicia",
        "neighbours": [
            {"name": "boh", "shared_coast": False},
            {"name": "bud", "shared_coast": False},
            {"name": "rum", "shared_coast": False},
            {"name": "sil", "shared_coast": False},
            {"name": "ukr", "shared_coast": False},
            {"name": "vie", "shared_coast": False},
            {"name": "war", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "gas": {
        "display_name": "Gascony",
        "nation": "france",
        "neighbours": [
            {"name": "bre", "shared_coast": True},
            {"name": "bur", "shared_coast": False},
            {"name": "mar", "shared_coast": False},
            {"name": "mid", "shared_coast": False},
            {"name": "par", "shared_coast": False},
            {"name": "spa", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "gol": {
        "display_name": "Gulf of Lyon",
        "neighbours": [
            {"name": "mar", "shared_coast": False},
            {"name": "pie", "shared_coast": False},
            {"name": "spa", "shared_coast": False},
            {"name": "tus", "shared_coast": False},
            {"name": "tyn", "shared_coast": False},
            {"name": "wes", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "gre": {
        "display_name": "Greece",
        "neighbours": [
            {"name": "aeg", "shared_coast": False},
            {"name": "alb", "shared_coast": True},
            {"name": "bul", "shared_coast": True},
            {"name": "ion", "shared_coast": False},
            {"name": "ser", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "hel": {
        "display_name": "Helgoand Bight",
        "neighbours": [
            {"name": "den", "shared_coast": False},
            {"name": "hol", "shared_coast": False},
            {"name": "kie", "shared_coast": False},
            {"name": "nth", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "hol": {
        "display_name": "Holland",
        "neighbours": [
            {"name": "bel", "shared_coast": True},
            {"name": "hel", "shared_coast": False},
            {"name": "kie", "shared_coast": True},
            {"name": "nth", "shared_coast": False},
            {"name": "ruh", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "ion": {
        "display_name": "Ionian Sea",
        "neighbours": [
            {"name": "aeg", "shared_coast": False},
            {"name": "alb", "shared_coast": False},
            {"name": "apu", "shared_coast": False},
            {"name": "gre", "shared_coast": False},
            {"name": "nap", "shared_coast": False},
            {"name": "tun", "shared_coast": False},
            {"name": "tyn", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "iri": {
        "display_name": "Irish Sea",
        "neighbours": [
            {"name": "eng", "shared_coast": False},
            {"name": "lvp", "shared_coast": False},
            {"name": "mid", "shared_coast": False},
            {"name": "nat", "shared_coast": False},
            {"name": "wal", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "kie": {
        "display_name": "Kiel",
        "nation": "germany",
        "neighbours": [
            {"name": "bal", "shared_coast": False},
            {"name": "ber", "shared_coast": True},
            {"name": "den", "shared_coast": True},
            {"name": "hel", "shared_coast": False},
            {"name": "hol", "shared_coast": True},
            {"name": "mun", "shared_coast": False},
            {"name": "ruh", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "lon": {
        "display_name": "London",
        "nation": "england",
        "neighbours": [
            {"name": "eng", "shared_coast": False},
            {"name": "nth", "shared_coast": False},
            {"name": "wal", "shared_coast": True},
            {"name": "yor", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "lvn": {
        "display_name": "Livonia",
        "neighbours": [
            {"name": "bal", "shared_coast": False},
            {"name": "bot", "shared_coast": False},
            {"name": "mos", "shared_coast": False},
            {"name": "pru", "shared_coast": True},
            {"name": "stp", "shared_coast": True},
            {"name": "war", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "lvp": {
        "display_name": "Liverpool",
        "nation": "england",
        "neighbours": [
            {"name": "cly", "shared_coast": True},
            {"name": "edi", "shared_coast": False},
            {"name": "iri", "shared_coast": False},
            {"name": "nat", "shared_coast": False},
            {"name": "wal", "shared_coast": True},
            {"name": "yor", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "mar": {
        "display_name": "Marseilles",
        "nation": "france",
        "neighbours": [
            {"name": "bur", "shared_coast": False},
            {"name": "gas", "shared_coast": False},
            {"name": "gol", "shared_coast": False},
            {"name": "pie", "shared_coast": True},
            {"name": "spa", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "mid": {
        "display_name": "Mid Atlantic",
        "neighbours": [
            {"name": "bre", "shared_coast": False},
            {"name": "eng", "shared_coast": False},
            {"name": "gas", "shared_coast": False},
            {"name": "iri", "shared_coast": False},
            {"name": "naf", "shared_coast": False},
            {"name": "nat", "shared_coast": False},
            {"name": "spa", "shared_coast": False},
            {"name": "por", "shared_coast": False},
            {"name": "wes", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "mos": {
        "display_name": "Moscow",
        "nation": "russia",
        "neighbours": [
            {"name": "arm", "shared_coast": False},
            {"name": "bla", "shared_coast": False},
            {"name": "mos", "shared_coast": False},
            {"name": "rum", "shared_coast": False},
            {"name": "sev", "shared_coast": False},
            {"name": "ukr", "shared_coast": False},
            {"name": "war", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "mun": {
        "display_name": "Munich",
        "nation": "germany",
        "neighbours": [
            {"name": "ber", "shared_coast": False},
            {"name": "boh", "shared_coast": False},
            {"name": "bur", "shared_coast": False},
            {"name": "kie", "shared_coast": False},
            {"name": "sil", "shared_coast": False},
            {"name": "ruh", "shared_coast": False},
            {"name": "tyr", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "naf": {
        "display_name": "North Africa",
        "neighbours": [
            {"name": "mid", "shared_coast": False},
            {"name": "tun", "shared_coast": True},
            {"name": "wes", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "nap": {
        "display_name": "Naples",
        "nation": "italy",
        "neighbours": [
            {"name": "apu", "shared_coast": True},
            {"name": "ion", "shared_coast": False},
            {"name": "rom", "shared_coast": True},
            {"name": "tyn", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "nat": {
        "display_name": "North Atlantic",
        "neighbours": [
            {"name": "cly", "shared_coast": False},
            {"name": "iri", "shared_coast": False},
            {"name": "lvp", "shared_coast": False},
            {"name": "mid", "shared_coast": False},
            {"name": "nrg", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "nrg": {
        "display_name": "Norwegian Sea",
        "neighbours": [
            {"name": "bar", "shared_coast": False},
            {"name": "cly", "shared_coast": False},
            {"name": "edi", "shared_coast": False},
            {"name": "nat", "shared_coast": False},
            {"name": "nry", "shared_coast": False},
            {"name": "nth", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "nth": {
        "display_name": "North Sea",
        "neighbours": [
            {"name": "bel", "shared_coast": False},
            {"name": "den", "shared_coast": False},
            {"name": "edi", "shared_coast": False},
            {"name": "eng", "shared_coast": False},
            {"name": "hel", "shared_coast": False},
            {"name": "hol", "shared_coast": False},
            {"name": "lon", "shared_coast": False},
            {"name": "nrg", "shared_coast": False},
            {"name": "nwy", "shared_coast": False},
            {"name": "ska", "shared_coast": False},
            {"name": "yor", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "nwy": {
        "display_name": "Norway",
        "nation": "neutral",
        "neighbours": [
            {"name": "bar", "shared_coast": False},
            {"name": "fin", "shared_coast": False},
            {"name": "nrg", "shared_coast": False},
            {"name": "nth", "shared_coast": False},
            {"name": "ska", "shared_coast": False},
            {"name": "stp", "shared_coast": True},
            {"name": "swe", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "par": {
        "display_name": "Paris",
        "nation": "france",
        "neighbours": [
            {"name": "bre", "shared_coast": False},
            {"name": "bur", "shared_coast": False},
            {"name": "gas", "shared_coast": False},
            {"name": "pic", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "pic": {
        "display_name": "Picardy",
        "neighbours": [
            {"name": "bre", "shared_coast": True},
            {"name": "bel", "shared_coast": True},
            {"name": "bur", "shared_coast": False},
            {"name": "eng", "shared_coast": False},
            {"name": "par", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "pie": {
        "display_name": "Piedmont",
        "neighbours": [
            {"name": "gol", "shared_coast": False},
            {"name": "mar", "shared_coast": True},
            {"name": "tus", "shared_coast": True},
            {"name": "tyr", "shared_coast": False},
            {"name": "ven", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "por": {
        "display_name": "Portugal",
        "neighbours": [
            {"name": "mid", "shared_coast": False},
            {"name": "spa", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "rom": {
        "display_name": "Rome",
        "nation": "italy",
        "neighbours": [
            {"name": "apu", "shared_coast": False},
            {"name": "nap", "shared_coast": True},
            {"name": "tus", "shared_coast": True},
            {"name": "tyn", "shared_coast": False},
            {"name": "ven", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "ruh": {
        "display_name": "Ruhr",
        "nation": "germany",
        "neighbours": [
            {"name": "bel", "shared_coast": False},
            {"name": "bur", "shared_coast": False},
            {"name": "hol", "shared_coast": False},
            {"name": "kie", "shared_coast": False},
            {"name": "mun", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "rum": {
        "display_name": "Rumania",
        "neighbours": [
            {"name": "bla", "shared_coast": False},
            {"name": "bud", "shared_coast": False},
            {"name": "bul", "shared_coast": True},
            {"name": "gal", "shared_coast": False},
            {"name": "ser", "shared_coast": False},
            {"name": "sev", "shared_coast": True},
            {"name": "ukr", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "pru": {
        "display_name": "Prussia",
        "neighbours": [
            {"name": "bal", "shared_coast": False},
            {"name": "ber", "shared_coast": True},
            {"name": "lvn", "shared_coast": True},
            {"name": "sil", "shared_coast": False},
            {"name": "war", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "ser": {
        "display_name": "Serbia",
        "neighbours": [
            {"name": "alb", "shared_coast": False},
            {"name": "bud", "shared_coast": False},
            {"name": "bul", "shared_coast": False},
            {"name": "gre", "shared_coast": False},
            {"name": "rum", "shared_coast": False},
            {"name": "tri", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "sev": {
        "display_name": "Sevastopol",
        "nation": "russia",
        "neighbours": [
            {"name": "arm", "shared_coast": True},
            {"name": "bla", "shared_coast": False},
            {"name": "mos", "shared_coast": False},
            {"name": "rum", "shared_coast": True},
            {"name": "ukr", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "sil": {
        "display_name": "Silesia",
        "neighbours": [
            {"name": "ber", "shared_coast": False},
            {"name": "boh", "shared_coast": False},
            {"name": "gal", "shared_coast": False},
            {"name": "mun", "shared_coast": False},
            {"name": "war", "shared_coast": False},
            ],
        "territory_type": "inland",
    },
    "ska": {
        "display_name": "Skagerrak",
        "neighbours": [
            {"name": "bal", "shared_coast": False},
            {"name": "den", "shared_coast": False},
            {"name": "nth", "shared_coast": False},
            {"name": "nwy", "shared_coast": False},
            {"name": "swe", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "smy": {
        "display_name": "Smyrna",
        "nation": "turkey",
        "neighbours": [
            {"name": "aeg", "shared_coast": False},
            {"name": "arm", "shared_coast": False},
            {"name": "ank", "shared_coast": False},
            {"name": "con", "shared_coast": True},
            {"name": "eas", "shared_coast": False},
            {"name": "syr", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "spa": {
        "display_name": "Spain",
        "neighbours": [
            {"name": "gas", "shared_coast": True},
            {"name": "gol", "shared_coast": False},
            {"name": "mar", "shared_coast": True},
            {"name": "mid", "shared_coast": False},
            {"name": "naf", "shared_coast": False},
            {"name": "por", "shared_coast": True},
            {"name": "wes", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "stp": {
        "display_name": "St. Petersburg",
        "nation": "russia",
        "neighbours": [
            {"name": "bar", "shared_coast": False},
            {"name": "bot", "shared_coast": False},
            {"name": "fin", "shared_coast": True},
            {"name": "lvn", "shared_coast": True},
            {"name": "mos", "shared_coast": False},
            {"name": "nwy", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "swe": {
        "display_name": "Sweden",
        "neighbours": [
            {"name": "bal", "shared_coast": False},
            {"name": "bot", "shared_coast": False},
            {"name": "den", "shared_coast": True},
            {"name": "fin", "shared_coast": True},
            {"name": "nwy", "shared_coast": True},
            {"name": "ska", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "syr": {
        "display_name": "Syria",
        "neighbours": [
            {"name": "arm", "shared_coast": False},
            {"name": "eas", "shared_coast": False},
            {"name": "smy", "shared_coast": True},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "tri": {
        "display_name": "Trieste",
        "nation": "austria",
        "neighbours": [
            {"name": "adr", "shared_coast": False},
            {"name": "alb", "shared_coast": True},
            {"name": "bud", "shared_coast": False},
            {"name": "ser", "shared_coast": False},
            {"name": "tyr", "shared_coast": False},
            {"name": "ven", "shared_coast": True},
            {"name": "vie", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "tun": {
        "display_name": "Tunisia",
        "neighbours": [
            {"name": "ion", "shared_coast": False},
            {"name": "naf", "shared_coast": True},
            {"name": "tyn", "shared_coast": False},
            {"name": "wes", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "tus": {
        "display_name": "Tuscany",
        "neighbours": [
            {"name": "gol", "shared_coast": False},
            {"name": "pie", "shared_coast": True},
            {"name": "rom", "shared_coast": True},
            {"name": "tyn", "shared_coast": False},
            {"name": "ven", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "tyr": {
        "display_name": "Tyrolia",
        "neighbours": [
            {"name": "boh", "shared_coast": False},
            {"name": "mun", "shared_coast": False},
            {"name": "tri", "shared_coast": False},
            {"name": "ven", "shared_coast": False},
            {"name": "vie", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "tyn": {
        "display_name": "Tyrhennian Sea",
        "neighbours": [
            {"name": "gol", "shared_coast": False},
            {"name": "ion", "shared_coast": False},
            {"name": "nap", "shared_coast": False},
            {"name": "rom", "shared_coast": False},
            {"name": "tun", "shared_coast": False},
            {"name": "tus", "shared_coast": False},
            {"name": "wes", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "ukr": {
        "display_name": "Ukraine",
        "neighbours": [
            {"name": "gal", "shared_coast": False},
            {"name": "mos", "shared_coast": False},
            {"name": "rum", "shared_coast": False},
            {"name": "sev", "shared_coast": False},
            {"name": "war", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "ven": {
        "display_name": "Venice",
        "nation": "italy",
        "neighbours": [
            {"name": "adr", "shared_coast": False},
            {"name": "apu", "shared_coast": True},
            {"name": "rom", "shared_coast": False},
            {"name": "pie", "shared_coast": False},
            {"name": "tri", "shared_coast": True},
            {"name": "tyn", "shared_coast": False},
            {"name": "tyr", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "vie": {
        "nation": "austria",
        "display_name": "Vienna",
        "neighbours": [
            {"name": "boh", "shared_coast": False},
            {"name": "bud", "shared_coast": False},
            {"name": "gal", "shared_coast": False},
            {"name": "tri", "shared_coast": False},
            {"name": "tyr", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "wal": {
        "display_name": "Wales",
        "neighbours": [
            {"name": "eng", "shared_coast": False},
            {"name": "iri", "shared_coast": False},
            {"name": "lon", "shared_coast": True},
            {"name": "lvp", "shared_coast": True},
            {"name": "yor", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply-center": False,
    },
    "war": {
        "display_name": "Warsaw",
        "nation": "russia",
        "neighbours": [
            {"name": "gal", "shared_coast": False},
            {"name": "lvn", "shared_coast": False},
            {"name": "mos", "shared_coast": False},
            {"name": "sil", "shared_coast": False},
            {"name": "pru", "shared_coast": False},
            {"name": "ukr", "shared_coast": False},
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "wes": {
        "display_name": "Western Mediterranean",
        "neighbours": [
            {"name": "gol", "shared_coast": False},
            {"name": "mid", "shared_coast": False},
            {"name": "naf", "shared_coast": False},
            {"name": "spa", "shared_coast": False},
            {"name": "tun", "shared_coast": False},
            {"name": "tyn", "shared_coast": False},
            ],
        "territory_type": "water",
        "supply_center": False,
    },
    "yor": {
        "display_name": "York",
        "neighbours": [
            {"name": "edi", "shared_coast": True},
            {"name": "lon", "shared_coast": True},
            {"name": "lvp", "shared_coast": False},
            {"name": "nth", "shared_coast": False},
            {"name": "wal", "shared_coast": False},
            ],
        "territory_type": "coastal",
        "supply-center": False,
    },
}