territories = {
    "apu": {
        "display_name": "Apulia",
        "neighbours": [
            "adr",
            "ion",
            "nap",
            "rom",
            "ven",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "boh": {
        "display_name": "Bohemia",
        "neighbours": [
            "gal",
            "mun",
            "sil",
            "tyr",
            "vie",
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "bre": {
        "display_name": "Brest",
        "owner": "france",
        "nation": "france",
        "neighbours": [
            "eng",
            "gas",
            "mid",
            "par",
            "pic",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "bur": {
        "display_name": "Burgundy",
        "neighbours": [
            "bre",
            "bel",
            "gas",
            "mar",
            "mun",
            "par",
            "pic",
            "ruh",
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "cly": {
        "display_name": "Liverpool",
        "neighbours": [
            "edi",
            "lvp",
            "iri",
            "nat",
            "nrg",
            ],
        "territory_type": "coastal",
        "supply-center": False,
    },
    "edi": {
        "display_name": "Edinburgh",
        "owner": "england",
        "nation": "england",
        "neighbours": [
            "cly",
            "lvp",
            "nth",
            "yor",
            "nat",
            "nrg",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "gas": {
        "display_name": "Gascony",
        "owner": "france",
        "nation": "france",
        "neighbours": [
            "bre",
            "bur",
            "mar",
            "mid",
            "par",
            "spa",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "lon": {
        "display_name": "London",
        "owner": "england",
        "nation": "england",
        "neighbours": [
            "eng",
            "nth",
            "wal",
            "yor",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "lvp": {
        "display_name": "Liverpool",
        "owner": "england",
        "nation": "england",
        "neighbours": [
            "cly",
            "edi",
            "iri",
            "nat",
            "wal",
            "yor",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "mar": {
        "display_name": "Marseilles",
        "owner": "france",
        "nation": "france",
        "neighbours": [
            "bur",
            "gas",
            "gol",
            "pie",
            "spa",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "naf": {
        "display_name": "North Africa",
        "neighbours": [
            "mid",
            "tun",
            "wes",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "nap": {
        "display_name": "Naples",
        "owner": "italy",
        "nation": "italy",
        "neighbours": [
            "apu",
            "ion",
            "rom",
            "tyn",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "par": {
        "display_name": "Paris",
        "owner": "france",
        "nation": "france",
        "neighbours": [
            "bre",
            "bur",
            "gas",
            "pic",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "pic": {
        "display_name": "Picardy",
        "neighbours": [
            "bre",
            "bel",
            "bur",
            "eng",
            "par",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "pie": {
        "display_name": "Piedmont",
        "neighbours": [
            "gol",
            "mar",
            "tus",
            "tyr",
            "ven",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "por": {
        "display_name": "Portugal",
        "owner": "neutral",
        "neighbours": [
            "mid",
            "spa",
            "spa-nc",
            "spa-sc",
            "bur",
            "eng",
            "par",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "rom": {
        "display_name": "Rome",
        "owner": "italy",
        "nation": "italy",
        "neighbours": [
            "apu",
            "nap",
            "tus",
            "tyn",
            "ven",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "tun": {
        "display_name": "Tunisia",
        "owner": "neutral",
        "neighbours": [
            "ion",
            "naf",
            "tyn",
            "wes",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "tus": {
        "display_name": "Tuscany",
        "neighbours": [
            "gol",
            "pie",
            "rom",
            "tyn",
            "ven",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "tyr": {
        "display_name": "Tyrolia",
        "neighbours": [
            "boh",
            "mun",
            "tri",
            "ven",
            "vie",
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "ven": {
        "display_name": "Venice",
        "owner": "italy",
        "nation": "italy",
        "neighbours": [
            "adr",
            "apu",
            "rom",
            "pie",
            "tri",
            "tyn",
            "tyr",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "wal": {
        "display_name": "Wales",
        "neighbours": [
            "eng",
            "iri",
            "lon",
            "lvp",
            "yor",
            ],
        "territory_type": "coastal",
        "supply-center": False,
    },
}