territories = {
    "adr": {
        "display_name": "Adriatic Sea",
        "neighbours": [
            "alb",
            "apu",
            "ion",
            "tri",
            "ven",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "aeg": {
        "display_name": "Aegean Sea",
        "neighbours": [
            "bla",
            "bul",
            "con",
            "eas",
            "gre",
            "ion",
            "smy",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "alb": {
        "display_name": "Albania",
        "neighbours": [
            "adr",
            "gre",
            "ion",
            "ser",
            "tri",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "ank": {
        "display_name": "Ankara",
        "nation": "turkey",
        "neighbours": [
            "arm",
            "bla",
            "con",
            "smy",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "apu": {
        "display_name": "Apulia",
        "neighbours": [
            "adr",
            "ion",
            "nap",
            "rom",
            "ven",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "arm": {
        "display_name": "Armenia",
        "nation": "turkey",
        "neighbours": [
            "ank",
            "bla",
            "sev",
            "smy",
            "syr",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "bal": {
        "display_name": "Baltic Sea",
        "neighbours": [
            "ber",
            "bot",
            "den",
            "kie",
            "lvn",
            "pru",
            "ska",
            "swe",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "bar": {
        "display_name": "Baltic Sea",
        "neighbours": [
            "nrg",
            "nry",
            "stp",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "ber": {
        "display_name": "Berlin",
        "nation": "germany",
        "neighbours": [
            "bal",
            "kie",
            "mun",
            "pru",
            "sil",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "bel": {
        "display_name": "Belgium",
        "neighbours": [
            "bur",
            "eng",
            "hol",
            "pic",
            "ruh",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "bla": {
        "display_name": "Black Sea",
        "neighbours": [
            "ank",
            "arm",
            "bul",
            "con",
            "rum",
            "sev",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "boh": {
        "display_name": "Bohemia",
        "neighbours": [
            "gal",
            "mun",
            "sil",
            "tyr",
            "vie",
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "bot": {
        "display_name": "Gulf of Bothnia",
        "neighbours": [
            "bal",
            "fin",
            "lvn",
            "swe",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "bre": {
        "display_name": "Brest",
        "nation": "france",
        "neighbours": [
            "eng",
            "gas",
            "mid",
            "par",
            "pic",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "bud": {
        "display_name": "Budapest",
        "nation": "austria",
        "neighbours": [
            "gal",
            "rum",
            "ser",
            "tri",
            "vie",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "bul": {
        "display_name": "Bulgaria",
        "neighbours": [
            "aeg",
            "bla",
            "con",
            "gre",
            "rum",
            "ser",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "bur": {
        "display_name": "Burgundy",
        "neighbours": [
            "bre",
            "bel",
            "gas",
            "mar",
            "mun",
            "par",
            "pic",
            "ruh",
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "cly": {
        "display_name": "Liverpool",
        "neighbours": [
            "edi",
            "lvp",
            "iri",
            "nat",
            "nrg",
            ],
        "territory_type": "coastal",
        "supply-center": False,
    },
    "con": {
        "display_name": "Constanstinople",
        "nation": "turkey",
        "neighbours": [
            "aeg",
            "ank",
            "bla",
            "bul",
            "smy",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "den": {
        "display_name": "Denmark",
        "neighbours": [
            "bal",
            "hel",
            "kie",
            "nth",
            "ska",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "eas": {
        "display_name": "Eastern Mediterranean Sea",
        "neighbours": [
            "aeg",
            "smy",
            "syr",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "edi": {
        "display_name": "Edinburgh",
        "nation": "england",
        "neighbours": [
            "cly",
            "lvp",
            "nth",
            "yor",
            "nat",
            "nrg",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "eng": {
        "display_name": "English Channel",
        "neighbours": [
            "bel",
            "bre",
            "iri",
            "lon",
            "mid",
            "nth",
            "pic",
            "wal",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "fin": {
        "display_name": "Finland",
        "neighbours": [
            "bot",
            "nwy",
            "stp",
            "swe",
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "gal": {
        "display_name": "Galicia",
        "neighbours": [
            "boh",
            "bud",
            "rum",
            "sil",
            "ukr",
            "vie",
            "war",
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "gas": {
        "display_name": "Gascony",
        "nation": "france",
        "neighbours": [
            "bre",
            "bur",
            "mar",
            "mid",
            "par",
            "spa",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "gol": {
        "display_name": "Gulf of Lyon",
        "neighbours": [
            "mar",
            "pie",
            "spa",
            "tus",
            "tyn",
            "wes",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "gre": {
        "display_name": "Greece",
        "neighbours": [
            "aeg",
            "alb",
            "bul",
            "ion",
            "ser",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "hel": {
        "display_name": "Helgoand Bight",
        "neighbours": [
            "den",
            "hol",
            "kie",
            "nth",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "hol": {
        "display_name": "Holland",
        "neighbours": [
            "bel",
            "hel",
            "kie",
            "nth",
            "ruh",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "ion": {
        "display_name": "Ionian Sea",
        "neighbours": [
            "aeg",
            "alb",
            "apu",
            "gre",
            "nap",
            "tun",
            "tyn",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "iri": {
        "display_name": "Irish Sea",
        "neighbours": [
            "eng",
            "lvp",
            "mid",
            "nat",
            "wal",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "kie": {
        "display_name": "Kiel",
        "nation": "germany",
        "neighbours": [
            "bal",
            "bur",
            "den",
            "pic",
            "ruh",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "lon": {
        "display_name": "London",
        "nation": "england",
        "neighbours": [
            "eng",
            "nth",
            "wal",
            "yor",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "lvn": {
        "display_name": "Livonia",
        "neighbours": [
            "bal",
            "bot",
            "mos",
            "pru",
            "stp",
            "war",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "lvp": {
        "display_name": "Liverpool",
        "nation": "england",
        "neighbours": [
            "cly",
            "edi",
            "iri",
            "nat",
            "wal",
            "yor",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "mar": {
        "display_name": "Marseilles",
        "nation": "france",
        "neighbours": [
            "bur",
            "gas",
            "gol",
            "pie",
            "spa",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "mid": {
        "display_name": "Mid Atlantic",
        "neighbours": [
            "bre",
            "eng",
            "gas",
            "iri",
            "naf",
            "nat",
            "spa",
            "por",
            "wes",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "mos": {
        "display_name": "Moscow",
        "nation": "russia",
        "neighbours": [
            "arm",
            "bla",
            "mos",
            "rum",
            "sev",
            "ukr",
            "war",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "mun": {
        "display_name": "Munich",
        "nation": "germany",
        "neighbours": [
            "ber",
            "boh",
            "bur",
            "kie",
            "sil",
            "ruh",
            "tyr",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "naf": {
        "display_name": "North Africa",
        "neighbours": [
            "mid",
            "tun",
            "wes",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "nap": {
        "display_name": "Naples",
        "nation": "italy",
        "neighbours": [
            "apu",
            "ion",
            "rom",
            "tyn",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "nat": {
        "display_name": "North Atlantic",
        "neighbours": [
            "cly",
            "iri",
            "lvp",
            "mid",
            "nrg",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "nrg": {
        "display_name": "Norwegian Sea",
        "neighbours": [
            "bar",
            "cly",
            "edi",
            "nat",
            "nry",
            "nth",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "nth": {
        "display_name": "North Sea",
        "neighbours": [
            "bel",
            "den",
            "edi",
            "eng",
            "hel",
            "hol",
            "lon",
            "nrg",
            "nwy",
            "ska",
            "yor",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "par": {
        "display_name": "Paris",
        "nation": "france",
        "neighbours": [
            "bre",
            "bur",
            "gas",
            "pic",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "pic": {
        "display_name": "Picardy",
        "neighbours": [
            "bre",
            "bel",
            "bur",
            "eng",
            "par",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "pie": {
        "display_name": "Piedmont",
        "neighbours": [
            "gol",
            "mar",
            "tus",
            "tyr",
            "ven",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "por": {
        "display_name": "Portugal",
        "neighbours": [
            "mid",
            "spa",
            "bur",
            "eng",
            "par",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "rom": {
        "display_name": "Rome",
        "nation": "italy",
        "neighbours": [
            "apu",
            "nap",
            "tus",
            "tyn",
            "ven",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "ruh": {
        "display_name": "Ruhr",
        "nation": "germany",
        "neighbours": [
            "bel",
            "bur",
            "hol",
            "kie",
            "mun",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "rum": {
        "display_name": "Rumania",
        "neighbours": [
            "bla",
            "bud",
            "bul",
            "gal",
            "ser",
            "sev",
            "ukr",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "pru": {
        "display_name": "Prussia",
        "neighbours": [
            "bal",
            "ber",
            "lvn",
            "sil",
            "war",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "ser": {
        "display_name": "Serbia",
        "neighbours": [
            "alb",
            "bud",
            "bul",
            "gre",
            "rum",
            "tri",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "sev": {
        "display_name": "Sevastapol",
        "nation": "russia",
        "neighbours": [
            "arm",
            "bla",
            "mos",
            "rum",
            "ukr",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "sil": {
        "display_name": "Silesia",
        "neighbours": [
            "ber",
            "boh",
            "gal",
            "mun",
            "war",
            ],
        "territory_type": "inland",
    },
    "ska": {
        "display_name": "Skagerrak",
        "neighbours": [
            "bal",
            "den",
            "nth",
            "nwy",
            "swe",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "smy": {
        "display_name": "Smyrna",
        "nation": "turkey",
        "neighbours": [
            "aeg",
            "arm",
            "ank",
            "con",
            "eas",
            "syr",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "spa": {
        "display_name": "Spain",
        "neighbours": [
            "gas",
            "lyo",
            "mar",
            "mid",
            "naf",
            "por",
            "wes",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "stp": {
        "display_name": "St. Petersburg",
        "nation": "russia",
        "neighbours": [
            "bar",
            "bot",
            "fin",
            "lvn",
            "mos",
            ],
        "territory_type": "coastal",
        "supply-center": True,
    },
    "swe": {
        "display_name": "Sweden",
        "neighbours": [
            "bal",
            "bot",
            "den",
            "fin",
            "nwy",
            "ska",
            "swe",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "syr": {
        "display_name": "Syria",
        "neighbours": [
            "arm",
            "eas",
            "smy",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "tri": {
        "display_name": "Trieste",
        "nation": "austria",
        "neighbours": [
            "adr",
            "alb",
            "bud",
            "ser",
            "tyr",
            "vie",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "tun": {
        "display_name": "Tunisia",
        "neighbours": [
            "ion",
            "naf",
            "tyn",
            "wes",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "tus": {
        "display_name": "Tuscany",
        "neighbours": [
            "gol",
            "pie",
            "rom",
            "tyn",
            "ven",
            ],
        "territory_type": "coastal",
        "supply_center": False,
    },
    "tyr": {
        "display_name": "Tyrolia",
        "neighbours": [
            "boh",
            "mun",
            "tri",
            "ven",
            "vie",
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "tyn": {
        "display_name": "Tyrhennian Sea",
        "neighbours": [
            "gol",
            "ion",
            "nap",
            "rom",
            "tun",
            "tus",
            "wes",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "ukr": {
        "display_name": "Ukraine",
        "neighbours": [
            "gal",
            "mos",
            "rum",
            "sev",
            "war",
            ],
        "territory_type": "inland",
        "supply_center": False,
    },
    "ven": {
        "display_name": "Venice",
        "nation": "italy",
        "neighbours": [
            "adr",
            "apu",
            "rom",
            "pie",
            "tri",
            "tyn",
            "tyr",
            ],
        "territory_type": "coastal",
        "supply_center": True,
    },
    "vie": {
        "nation": "austria",
        "display_name": "Vienna",
        "neighbours": [
            "boh",
            "bud",
            "gal",
            "tri",
            "tyr",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "wal": {
        "display_name": "Wales",
        "neighbours": [
            "eng",
            "iri",
            "lon",
            "lvp",
            "yor",
            ],
        "territory_type": "coastal",
        "supply-center": False,
    },
    "war": {
        "display_name": "Warsaw",
        "nation": "russia",
        "neighbours": [
            "gal",
            "lvn",
            "mos",
            "sil",
            "pru",
            "ukr",
            ],
        "territory_type": "inland",
        "supply_center": True,
    },
    "wes": {
        "display_name": "Western Mediterranean",
        "neighbours": [
            "gol",
            "mid",
            "naf",
            "spa",
            "tun",
            "tyn",
            ],
        "territory_type": "sea",
        "supply_center": False,
    },
    "yor": {
        "display_name": "York",
        "neighbours": [
            "edi",
            "lon",
            "lvp",
            "nth",
            "wal",
            ],
        "territory_type": "coastal",
        "supply-center": False,
    },
}