# Generated by Django 2.2.5 on 2019-10-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='NamedCoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map_abbreviation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'named_coast',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nation',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('S', 'Spring'), ('F', 'Fall')], max_length=1)),
                ('type', models.CharField(choices=[('O', 'Order'), ('R', 'Retreat and Disband'), ('B', 'Build and Disband')], max_length=1)),
            ],
            options={
                'db_table': 'phase',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('land', 'Land'), ('sea', 'Sea')], max_length=10)),
                ('coastal', models.BooleanField(default=False)),
                ('controlled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlled_territories', to='core.Nation')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_territories', to='core.Nation')),
                ('neighbours', models.ManyToManyField(blank=True, related_name='_territory_neighbours_+', to='core.Territory')),
                ('shared_coasts', models.ManyToManyField(related_name='_territory_shared_coasts_+', to='core.Territory')),
            ],
            options={
                'db_table': 'territory',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('current_turn', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Game')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Phase')),
            ],
            options={
                'db_table': 'turn',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('army', 'Army'), ('fleet', 'Fleet')], default='army', max_length=50)),
                ('dislodged_state', models.CharField(choices=[('unresolved', 'Unresolved'), ('sustains', 'Sustains'), ('dislodged', 'Dislodged')], default='unresolved', max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('dislodged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Piece')),
                ('named_coast', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.NamedCoast')),
                ('nation', models.ForeignKey(db_column='nation_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.Nation')),
                ('territory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Territory')),
            ],
            options={
                'db_table': 'piece',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalised', models.BooleanField(default=False)),
                ('nation', models.ForeignKey(db_column='nation_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.Nation')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turn')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='namedcoast',
            name='neighbours',
            field=models.ManyToManyField(blank=True, related_name='named_coast_neighbours', to='core.Territory'),
        ),
        migrations.AddField(
            model_name='namedcoast',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_coasts', to='core.Territory'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.Nation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.Nation')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hold', 'Hold'), ('move', 'Move'), ('support', 'Support'), ('convoy', 'Convoy'), ('retreat', 'Retreat'), ('build', 'Build'), ('disband', 'Disband')], default='hold', max_length=8)),
                ('state', models.CharField(choices=[('unresolved', 'Unresolved'), ('succeeds', 'Succeeds'), ('fails', 'Fails')], default='unresolved', max_length=15)),
                ('piece_type', models.CharField(blank=True, choices=[('army', 'Army'), ('fleet', 'Fleet')], max_length=50, null=True)),
                ('illegal', models.BooleanField(default=False)),
                ('illegal_message', models.CharField(blank=True, max_length=500, null=True)),
                ('success', models.BooleanField(default=True)),
                ('bounced', models.BooleanField(default=False)),
                ('result_message', models.CharField(blank=True, max_length=100, null=True)),
                ('aux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Territory')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Order')),
                ('piece', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Piece')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Territory')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Territory')),
                ('target_coast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.NamedCoast')),
            ],
            options={
                'db_table': 'command',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.Nation')),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='SupplyCenter',
            fields=[
                ('territory', models.OneToOneField(db_column='territory_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supply_center', serialize=False, to='core.Territory')),
                ('initial_piece_type', models.CharField(choices=[('army', 'Army'), ('fleet', 'Fleet')], max_length=50)),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_supply_centers', to='core.Nation')),
            ],
            options={
                'db_table': 'supply_center',
            },
        ),
        migrations.AddConstraint(
            model_name='namedcoast',
            constraint=models.UniqueConstraint(fields=('parent', 'map_abbreviation'), name='unique_coast_abbreviation'),
        ),
        migrations.AddConstraint(
            model_name='namedcoast',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_coast_name'),
        ),
    ]
