# Generated by Django 2.2.10 on 2020-05-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryMapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('text_x', models.FloatField()),
                ('text_y', models.FloatField()),
                ('piece_x', models.FloatField()),
                ('piece_y', models.FloatField()),
                ('dislodged_piece_x', models.FloatField()),
                ('dislodged_piece_y', models.FloatField()),
                ('supply_center_x', models.FloatField()),
                ('supply_center_y', models.FloatField()),
                ('territory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_data', to='core.Territory')),
            ],
        ),
    ]
