# Generated by Django 2.2.5 on 2019-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='num_players',
            new_name='max_num_players',
        ),
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.PositiveIntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('ended', 'Ended')], default='pending', max_length=22),
        ),
    ]
