# Generated by Django 2.2.5 on 2019-10-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='_max_attack_strength_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='_max_defend_strength_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='_max_hold_strength_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='_max_prevent_strength_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='_min_attack_strength_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='_min_defend_strength_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='_min_hold_strength_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='_min_prevent_strength_result',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
