# Generated by Django 2.2.5 on 2019-10-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='piece_type',
            field=models.CharField(choices=[('army', 'Army'), ('fleet', 'Fleet')], max_length=50, null=True),
        ),
    ]
