# Generated by Django 3.0.7 on 2020-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='flag',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
