# Generated by Django 3.0.7 on 2020-07-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nation_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
