# Generated by Django 2.2.10 on 2020-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_territorymapdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorymapdata',
            name='dislodged_piece_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='territorymapdata',
            name='dislodged_piece_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='territorymapdata',
            name='piece_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='territorymapdata',
            name='piece_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='territorymapdata',
            name='supply_center_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='territorymapdata',
            name='supply_center_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='territorymapdata',
            name='text_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='territorymapdata',
            name='text_y',
            field=models.FloatField(null=True),
        ),
    ]
