# Generated by Django 2.2.5 on 2020-04-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200410_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turn',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
