# Generated by Django 3.1.7 on 2021-04-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210305_1627'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turn',
            name='unique_phase_per_game,',
        ),
        migrations.AddField(
            model_name='turn',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turn',
            name='restored_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turn'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(fields=('game', 'year', 'season', 'phase', 'restored_from'), name='unique_phase_per_game,'),
        ),
    ]
