# Generated by Django 2.2.5 on 2019-10-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_command_piece_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='piece_type',
            field=models.CharField(blank=True, choices=[('army', 'Army'), ('fleet', 'Fleet')], max_length=50, null=True),
        ),
    ]
