# Generated by Django 2.2.10 on 2020-05-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200509_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorymapdata',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='territorymapdata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
