# Generated by Django 2.2.5 on 2019-11-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='country_choice_mode',
            new_name='nation_choice_mode',
        ),
    ]
