# Generated by Django 2.2.5 on 2019-11-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191130_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='initial_piece_type',
            field=models.CharField(choices=[('army', 'Army'), ('fleet', 'Fleet')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='territory',
            name='supply_center',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SupplyCenter',
        ),
    ]
