# Generated by Django 2.2.5 on 2020-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200410_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='outcome',
            field=models.CharField(blank=True, choices=[('moves', 'Moves'), ('resolved', 'Resolved'), ('bounced', 'Bounced'), ('illegal', 'Illegal'), ('aux failed', 'Aux failed'), ('aux does not correspond', 'Aux does not correspond')], max_length=25, null=True),
        ),
    ]
