# Generated by Django 3.1.7 on 2021-04-22 12:09

from django.db import migrations


def title_case_territory_names(apps, schema_editor):
    Territory = apps.get_model('core', 'Territory')
    for territory in Territory.objects.all():
        territory.name = territory.name.title()
        territory.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210409_0949'),
    ]

    operations = [
        migrations.RunPython(
            title_case_territory_names,
            reverse_code=migrations.RunPython.noop
        ),
    ]
