# Generated by Django 2.2.5 on 2019-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_command_order_not_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='via_convoy',
            field=models.BooleanField(default=False),
        ),
    ]
