# Generated by Django 2.2.5 on 2019-10-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191006_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='valid',
        ),
        migrations.AddField(
            model_name='command',
            name='bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='command',
            name='illegal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='command',
            name='illegal_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='dislodged_state',
            field=models.CharField(choices=[('unresolved', 'Unresolved'), ('sustains', 'Sustains'), ('dislodged', 'Dislodged')], default='unresolved', max_length=15),
        ),
        migrations.AlterField(
            model_name='namedcoast',
            name='map_abbreviation',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='namedcoast',
            constraint=models.UniqueConstraint(fields=('parent', 'map_abbreviation'), name='unique_coast_abbreviation'),
        ),
        migrations.AddConstraint(
            model_name='namedcoast',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_coast_name'),
        ),
    ]
