# Generated by Django 3.0.7 on 2020-07-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_variant_identifier'),
        ('core', '0004_auto_20200714_1820'),
    ]

    operations = [
    ]
