# Generated by Django 2.2.5 on 2019-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_command_via_convoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='retreat_territories',
            field=models.ManyToManyField(blank=True, null=True, related_name='retreat_pieces', to='core.Territory'),
        ),
    ]
