# Generated by Django 2.2.5 on 2019-11-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191130_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationstate',
            name='orders_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
