# Generated by Django 2.2.5 on 2019-12-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191130_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Territory'),
            preserve_default=False,
        ),
    ]
