# Generated by Django 2.2.5 on 2019-10-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_piece_retreat_territories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='_max_attack_strength_result',
        ),
        migrations.RemoveField(
            model_name='command',
            name='_max_defend_strength_result',
        ),
        migrations.RemoveField(
            model_name='command',
            name='_max_hold_strength_result',
        ),
        migrations.RemoveField(
            model_name='command',
            name='_max_prevent_strength_result',
        ),
        migrations.RemoveField(
            model_name='command',
            name='_min_attack_strength_result',
        ),
        migrations.RemoveField(
            model_name='command',
            name='_min_defend_strength_result',
        ),
        migrations.RemoveField(
            model_name='command',
            name='_min_hold_strength_result',
        ),
        migrations.RemoveField(
            model_name='command',
            name='_min_prevent_strength_result',
        ),
        migrations.RemoveField(
            model_name='command',
            name='bounced',
        ),
        migrations.RemoveField(
            model_name='command',
            name='order_not_changed',
        ),
        migrations.RemoveField(
            model_name='command',
            name='result_message',
        ),
        migrations.RemoveField(
            model_name='command',
            name='success',
        ),
        migrations.AlterField(
            model_name='piece',
            name='retreat_territories',
            field=models.ManyToManyField(blank=True, related_name='retreat_pieces', to='core.Territory'),
        ),
    ]
