# Generated by Django 2.2.5 on 2019-10-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191020_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Territory'),
        ),
    ]
