# Generated by Django 2.2.10 on 2020-05-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200509_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TerritoryMapData',
        ),
    ]
