# Generated by Django 2.2.5 on 2019-12-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191201_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='territory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.Territory'),
        ),
    ]
