# Generated by Django 2.2.5 on 2019-11-06 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191031_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='territory',
            name='controlled_by',
        ),
        migrations.CreateModel(
            name='TerritoryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlled_territories', to='core.Nation')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Territory')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_states', to='core.Turn')),
            ],
        ),
        migrations.CreateModel(
            name='GameNation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surrendered', models.BooleanField(default=False, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Game')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Nation')),
                ('surrendered_turn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Turn')),
            ],
        ),
    ]
