# Generated by Django 2.2.5 on 2020-04-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200410_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='attacker_territory',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='dislodged',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='dislodged_by',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='named_coast',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='persisted_piece_id',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='territory',
        ),
        migrations.AddField(
            model_name='piece',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.Game'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PieceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislodged', models.BooleanField(default=False)),
                ('attacker_territory', models.ForeignKey(blank=True, help_text="If the piece was dislodged via a land attack, the piece cannot to the attacking piece's territory.", null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Territory')),
                ('dislodged_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piece_disloged', to='core.PieceState')),
                ('named_coast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.NamedCoast')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.Piece')),
                ('territory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.Territory')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piecestates', to='core.Turn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
