# Generated by Django 2.2.5 on 2019-11-07 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191031_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='turn',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Turn'),
            preserve_default=False,
        ),
    ]
