# Generated by Django 2.2.5 on 2019-11-07 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_piece_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.Turn'),
        ),
    ]
