# Generated by Django 2.2.5 on 2019-11-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191106_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='controlled_by_initial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initially_controlled_territories', to='core.Nation'),
        ),
    ]
