# Generated by Django 2.2.5 on 2019-12-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191215_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='named_coast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.NamedCoast'),
        ),
    ]
