# Generated by Django 2.2.10 on 2020-05-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mapdata_territorymapdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdata',
            name='identifier',
            field=models.CharField(default='normal', max_length=200),
            preserve_default=False,
        ),
    ]
