# Generated by Django 3.1.2 on 2020-10-31 12:55

from django.db import migrations, models
from django.utils.text import slugify


def add_identifier_to_territories(apps, schema_editor):
    Territory = apps.get_model('core', 'Territory')
    all_territories = Territory.objects.all().select_related('variant')
    for territory in all_territories:
        uid = slugify('-'.join([territory.variant.name, territory.name]))
        territory.uid = uid
        territory.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201011_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='uid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(
            add_identifier_to_territories,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='territory',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='territory',
            unique_together={('name', 'variant')},
        ),
    ]
