# Generated by Django 2.2.5 on 2020-04-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200412_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='turn',
        ),
    ]
