# Generated by Django 2.2.5 on 2019-11-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191107_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='season',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], default='spring', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turn',
            name='phase',
            field=models.CharField(choices=[('order', 'Order'), ('retreat and disband', 'Retreat and Disband'), ('build', 'Build')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
