# Generated by Django 3.1.2 on 2020-10-31 13:10

from django.db import migrations, models
from django.utils.text import slugify


def add_identifier_to_nations(apps, schema_editor):
    Nation = apps.get_model('core', 'Nation')
    all_nations = Nation.objects.all().select_related('variant')
    for nation in all_nations:
        uid = slugify('-'.join([nation.variant.name, nation.name]))
        nation.uid = uid
        nation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201031_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='uid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(
            add_identifier_to_nations,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='nation',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='nation',
            unique_together={('name', 'variant')},
        ),
    ]
