# Generated by Django 3.1.7 on 2021-04-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210426_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='turn_destroyed',
            field=models.ForeignKey(blank=True, help_text='The turn during which this piece was destroyed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.turn'),
        ),
    ]
