# Generated by Django 3.0.6 on 2020-05-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200509_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedcoast',
            name='piece_starts_here',
            field=models.BooleanField(default=False),
        ),
    ]
