# Generated by Django 3.2 on 2021-05-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_piece_turn_destroyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecestate',
            name='dislodged_from',
            field=models.ForeignKey(blank=True, help_text="True if the piece was dislodged via a land attack during this turn. The piece's attacker_territory field will be set to this value next turn.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_dislodged_from_here', to='core.territory'),
        ),
    ]
