# Generated by Django 2.2.5 on 2019-11-07 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191107_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='core.Game'),
        ),
    ]
