# Generated by Django 3.1.2 on 2020-10-31 15:07

from django.db import migrations, models
from django.utils.text import slugify


def add_identifier_to_named_coasts(apps, schema_editor):
    NamedCoast = apps.get_model('core', 'NamedCoast')
    all_named_coasts = NamedCoast.objects.all()
    for named_coast in all_named_coasts:
        uid = slugify('-'.join([named_coast.parent.variant.name, named_coast.name]))
        named_coast.uid = uid
        named_coast.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201031_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedcoast',
            name='uid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(
            add_identifier_to_named_coasts,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='namedcoast',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
