# Generated by Django 2.2.5 on 2019-11-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_territory_controlled_by_initial'),
        ('core', '0010_auto_20191107_2121'),
    ]

    operations = [
    ]
