# Generated by Django 3.1.2 on 2020-10-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201031_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedcoastmapdata',
            name='map_data',
        ),
        migrations.RemoveField(
            model_name='namedcoastmapdata',
            name='named_coast',
        ),
        migrations.RemoveField(
            model_name='territorymapdata',
            name='map_data',
        ),
        migrations.RemoveField(
            model_name='territorymapdata',
            name='territory',
        ),
        migrations.DeleteModel(
            name='MapData',
        ),
        migrations.DeleteModel(
            name='NamedCoastMapData',
        ),
        migrations.DeleteModel(
            name='TerritoryMapData',
        ),
    ]
