# Generated by Django 3.1.3 on 2020-11-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201031_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnend',
            name='turn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.turn'),
        ),
    ]
