# Generated by Django 3.1.2 on 2020-11-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201031_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territory',
            options={'verbose_name_plural': 'territories'},
        ),
    ]
