# Generated by Django 3.1.3 on 2020-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201031_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationstate',
            name='surrendered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
