# Generated by Django 3.0.6 on 2020-05-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200516_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='turn_created',
            field=models.ForeignKey(default=1, help_text='The turn during which this piece was created. Will always be a build phase unless the piece was one of the starting pieces.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Turn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='turn_disbanded',
            field=models.ForeignKey(help_text='The turn during which this piece was disbanded. Will always be a retreat/disband phase or a build/disband phase.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Turn'),
        ),
    ]
