# Generated by Django 2.2.5 on 2019-11-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191107_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationstate',
            name='game',
        ),
        migrations.AddField(
            model_name='nationstate',
            name='turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nation_states', to='core.Turn'),
            preserve_default=False,
        ),
    ]
