# Generated by Django 2.2.10 on 2020-05-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_turn_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='initial_piece_type',
            field=models.CharField(choices=[('army', 'Army'), ('fleet', 'Fleet')], max_length=50, null=True),
        ),
    ]
