# Generated by Django 3.1.3 on 2020-11-20 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20201112_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('canceled', 'Canceled'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='proposed', max_length=20)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('nations', models.ManyToManyField(related_name='draws', to='core.Nation')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_draws', to='core.nation')),
                ('proposed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='core.turn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='surrender',
            name='turn',
        ),
        migrations.AddField(
            model_name='surrender',
            name='nation_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surrenders', to='core.nationstate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='max_nations_in_draw',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(to='core.Nation'),
        ),
        migrations.AlterField(
            model_name='surrender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrenders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DrawResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.draw')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('draw', 'nation')},
            },
        ),
    ]
