# Generated by Django 3.0.6 on 2020-05-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200516_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='turn_disbanded',
            field=models.ForeignKey(blank=True, help_text='The turn during which this piece was disbanded. Will always be a retreat/disband phase or a build/disband phase.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Turn'),
        ),
    ]
