# Generated by Django 3.1.3 on 2020-11-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201120_2250'),
        ('core', '0012_auto_20201107_1255'),
        ('core', '0013_auto_20201107_2156'),
    ]

    operations = [
    ]
