# Generated by Django 2.2.5 on 2019-11-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191107_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationstate',
            name='surrendered_turn',
        ),
        migrations.AlterField(
            model_name='territorystate',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_states', to='core.Territory'),
        ),
    ]
