# Generated by Django 3.1.3 on 2020-12-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20201130_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='illegal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
