# Generated by Django 3.0.6 on 2020-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200516_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorymapdata',
            name='type',
            field=models.CharField(choices=[('land', 'Land'), ('sea', 'Sea')], default='land', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='outcome',
            field=models.CharField(blank=True, choices=[('moves', 'Moves'), ('resolved', 'Resolved'), ('bounced', 'Bounced'), ('aux_failed', 'Aux failed'), ('aux_does_not_correspond', 'Aux does not correspond'), ('succeeds', 'Succeeds'), ('fails', 'Fails')], max_length=25, null=True),
        ),
    ]
