# Generated by Django 3.1.3 on 2020-12-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_illegal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='legal',
        ),
        migrations.AddField(
            model_name='order',
            name='illegal',
            field=models.BooleanField(default=False),
        ),
    ]
