# Generated by Django 2.2.5 on 2019-11-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_nationstate_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationstate',
            old_name='player',
            new_name='user',
        ),
    ]
