# Generated by Django 2.2.5 on 2019-11-11 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_nationstate_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='persisted_piece_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='This ID is persisted across `Piece` instances to which belong to the same in game piece.'),
        ),
    ]
