# Generated by Django 2.2.5 on 2019-11-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191112_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='turn',
        ),
        migrations.AddField(
            model_name='order',
            name='nation_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.NationState'),
        ),
    ]
