# Generated by Django 3.0.6 on 2020-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_game_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='num_supply_centers_to_win',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
