# Generated by Django 2.2.5 on 2019-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191113_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('awaiting participants', 'Awaiting Participants'), ('pending', 'Pending'), ('live', 'Live'), ('ended', 'Ended')], default='awaiting participants', max_length=22),
        ),
    ]
