# Generated by Django 3.1.3 on 2020-12-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201206_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorystate',
            name='captured_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captured_territories', to='core.nation'),
        ),
    ]
