# Generated by Django 3.0.6 on 2020-05-23 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_variant_num_supply_centers_to_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(blank=True, through='core.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(blank=True, to='core.NationState'),
        ),
    ]
