# Generated by Django 2.2.5 on 2019-11-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191112_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCenterState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_center_states', to='core.Nation')),
                ('supply_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.SupplyCenter')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_center_states', to='core.Turn')),
            ],
        ),
    ]
