# Generated by Django 3.0.6 on 2020-05-25 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_auto_20200523_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(through='core.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(to='core.NationState'),
        ),
        migrations.AddConstraint(
            model_name='piecestate',
            constraint=models.UniqueConstraint(fields=('turn', 'territory', 'must_retreat'), name='unique_piece_in_territory,'),
        ),
    ]
