# Generated by Django 2.2.5 on 2019-11-12 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_supplycenterstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationstate',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationstate_states', to='core.Turn'),
        ),
        migrations.AlterField(
            model_name='nationstate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nation_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='piece',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_states', to='core.Turn'),
        ),
        migrations.AlterField(
            model_name='territorystate',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territorystate_states', to='core.Turn'),
        ),
    ]
