# Generated by Django 3.1.3 on 2020-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_territorystate_captured_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='next_phase',
            field=models.CharField(choices=[('order', 'Order'), ('retreat_and_disband', 'Retreat and Disband'), ('build', 'Build')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='next_season',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='next_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
