# Generated by Django 3.0.6 on 2020-05-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200525_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorystate',
            name='contested',
            field=models.BooleanField(default=False),
        ),
    ]
