# Generated by Django 2.2.5 on 2019-11-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.Variant'),
            preserve_default=False,
        ),
    ]
