# Generated by Django 2.2.5 on 2019-11-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_game_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
