# Generated by Django 3.0.6 on 2020-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_territorystate_contested'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorystate',
            name='bounce_occurred',
            field=models.BooleanField(default=False),
        ),
    ]
