# Generated by Django 3.0.6 on 2020-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_territorystate_bounce_occurred'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecestate',
            name='destroyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='piecestate',
            name='destroyed_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
