# Generated by Django 2.2.5 on 2019-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_game_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
