# Generated by Django 3.0.6 on 2020-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200530_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='outcome',
            field=models.CharField(blank=True, choices=[('moves', 'Moves'), ('resolved', 'Resolved'), ('bounced', 'Bounced'), ('aux_failed', 'Aux failed'), ('aux_does_not_correspond', 'Aux does not correspond'), ('succeeds', 'Succeeds'), ('given', 'Given'), ('fails', 'Fails')], max_length=25, null=True),
        ),
    ]
