# Generated by Django 2.2.5 on 2019-11-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_game_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='build_deadline',
            field=models.CharField(choices=[('twelve hours', '12 hours'), ('twenty four hours', '24 hours'), ('two days', '2 days'), ('three days', '3 days'), ('five days', '5 days'), ('seven days', '7 days')], default='twelve hours', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='order_deadline',
            field=models.CharField(choices=[('twelve hours', '12 hours'), ('twenty four hours', '24 hours'), ('two days', '2 days'), ('three days', '3 days'), ('five days', '5 days'), ('seven days', '7 days')], default='twenty four hours', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='retreat_deadline',
            field=models.CharField(choices=[('twelve hours', '12 hours'), ('twenty four hours', '24 hours'), ('two days', '2 days'), ('three days', '3 days'), ('five days', '5 days'), ('seven days', '7 days')], default='twenty four hours', max_length=100),
        ),
    ]
