# Generated by Django 3.0.6 on 2020-06-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200530_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='illegal_message',
            new_name='illegal_verbose',
        ),
        migrations.AddField(
            model_name='order',
            name='outcome_verbose',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
