# Generated by Django 3.0.6 on 2020-06-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0025_auto_20200612_1702'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table=None,
        ),
    ]
