# Generated by Django 2.2.5 on 2019-11-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20191123_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='finalised',
            new_name='illegal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='turn',
        ),
        migrations.AddField(
            model_name='order',
            name='aux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='illegal_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nation_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.NationState'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='piece',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Piece'),
        ),
        migrations.AddField(
            model_name='order',
            name='piece_type',
            field=models.CharField(blank=True, choices=[('army', 'Army'), ('fleet', 'Fleet')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('unresolved', 'Unresolved'), ('succeeds', 'Succeeds'), ('fails', 'Fails')], default='unresolved', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_coast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.NamedCoast'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('hold', 'Hold'), ('move', 'Move'), ('support', 'Support'), ('convoy', 'Convoy'), ('retreat', 'Retreat'), ('build', 'Build'), ('disband', 'Disband')], default='hold', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='via_convoy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Command',
        ),
    ]
