# Generated by Django 2.2.5 on 2019-11-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20191123_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='core.Variant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='territory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
