# Generated by Django 2.2.5 on 2019-11-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20191123_1413'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='announcement',
        ),
    ]
