# Generated by Django 2.1.7 on 2019-04-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Army'), ('F', 'Fleet')], max_length=1)),
                ('nation', models.ForeignKey(db_column='nation_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='service.Nation')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(db_column='nation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_centres', to='service.Nation')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=6)),
                ('display_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('L', 'Land'), ('S', 'Sea')], max_length=10)),
                ('coast', models.BooleanField(default=False)),
                ('neighours', models.ManyToManyField(blank=True, related_name='_territory_neighours_+', to='service.Territory')),
                ('shared_coasts', models.ManyToManyField(blank=True, related_name='_territory_shared_coasts_+', to='service.Territory')),
            ],
        ),
        migrations.AddField(
            model_name='supplycenter',
            name='territory',
            field=models.ForeignKey(db_column='territory_id', on_delete=django.db.models.deletion.CASCADE, related_name='supply_centre', to='service.Territory'),
        ),
    ]
