# Generated by Django 2.1.7 on 2019-07-27 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'challenge',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('H', 'Hold'), ('M', 'Move'), ('S', 'Support'), ('C', 'Convoy'), ('R', 'Retreat'), ('D', 'Disband'), ('B', 'Build')], max_length=1)),
                ('success', models.BooleanField(default=True)),
                ('result_message', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'command',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nation',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalised', models.BooleanField(default=False)),
                ('nation', models.ForeignKey(db_column='nation_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.Nation')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('S', 'Spring'), ('F', 'Fall')], max_length=1)),
                ('type', models.CharField(choices=[('O', 'Order'), ('R', 'Retreat and Disband'), ('B', 'Build and Disband')], max_length=1)),
            ],
            options={
                'db_table': 'phase',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_retreat', models.BooleanField(default=False)),
                ('must_disband', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('nation', models.ForeignKey(db_column='nation_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='service.Nation')),
            ],
            options={
                'db_table': 'piece',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('L', 'Land'), ('S', 'Sea')], max_length=10)),
                ('coastal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'territory',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('current_turn', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Game')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Phase')),
            ],
            options={
                'db_table': 'turn',
            },
        ),
        migrations.CreateModel(
            name='SupplyCenter',
            fields=[
                ('territory', models.OneToOneField(db_column='territory_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supply_center', serialize=False, to='service.Territory')),
                ('controlled_by', models.ForeignKey(db_column='nation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlled_supply_centers', to='service.Nation')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_supply_centers', to='service.Nation')),
            ],
            options={
                'db_table': 'supply_center',
            },
        ),
        migrations.AddField(
            model_name='territory',
            name='controlled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlled_territories', to='service.Nation'),
        ),
        migrations.AddField(
            model_name='territory',
            name='neighbours',
            field=models.ManyToManyField(blank=True, related_name='_territory_neighbours_+', to='service.Territory'),
        ),
        migrations.AddField(
            model_name='territory',
            name='shared_coasts',
            field=models.ManyToManyField(related_name='_territory_shared_coasts_+', to='service.Territory'),
        ),
        migrations.AddField(
            model_name='piece',
            name='territory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Turn'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='service.Nation'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='service.Nation'),
        ),
        migrations.AddField(
            model_name='command',
            name='aux_territory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aux_commands', to='service.Territory'),
        ),
        migrations.AddField(
            model_name='command',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='service.Order'),
        ),
        migrations.AddField(
            model_name='command',
            name='source_territory',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='source_commands', to='service.Territory'),
        ),
        migrations.AddField(
            model_name='command',
            name='target_territory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_commands', to='service.Territory'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='piece',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='service.Piece'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='service.Territory'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='service.Nation'),
        ),
    ]
