# Generated by Django 2.1.7 on 2019-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='type',
            field=models.CharField(choices=[('army', 'Army'), ('fleet', 'Fleet')], default='army', max_length=50),
        ),
    ]
