# Generated by Django 2.1.7 on 2019-05-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='territory',
            name='neighours',
        ),
        migrations.AddField(
            model_name='territory',
            name='neighbours',
            field=models.ManyToManyField(blank=True, related_name='_territory_neighbours_+', to='service.Territory'),
        ),
    ]
