# Generated by Django 2.1.7 on 2019-04-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='territory',
            field=models.ForeignKey(db_column='territory_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Territory'),
        ),
        migrations.AddField(
            model_name='territory',
            name='nationity',
            field=models.ForeignKey(db_column='nation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Nation'),
        ),
    ]
