# Generated by Django 2.1.7 on 2019-05-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190505_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='controlled_by',
            field=models.ForeignKey(db_column='controlled_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlled_territories', to='service.Nation'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='nationality',
            field=models.ForeignKey(db_column='nationality_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_territories', to='service.Nation'),
        ),
    ]
