# Generated by Django 2.1.7 on 2019-04-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190428_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplycenter',
            name='owner',
            field=models.ForeignKey(db_column='nation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_centers', to='service.Nation'),
        ),
        migrations.AlterField(
            model_name='supplycenter',
            name='territory',
            field=models.ForeignKey(db_column='territory_id', on_delete=django.db.models.deletion.CASCADE, related_name='supply_center', to='service.Territory'),
        ),
    ]
