# Generated by Django 2.1.7 on 2019-05-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190505_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='territory',
            name='nationality',
        ),
    ]
