# Generated by Django 2.1.7 on 2019-05-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_territory_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='result',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='result_display',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='territory',
            field=models.ForeignKey(db_column='territory_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='service.Territory'),
        ),
    ]
