# Generated by Django 2.1.7 on 2019-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_command_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(choices=[('hold', 'Hold'), ('move', 'Fleet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='territory',
            name='type',
            field=models.CharField(choices=[('land', 'Land'), ('sea', 'Sea')], max_length=10),
        ),
    ]
