# Generated by Django 2.1.7 on 2019-05-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190506_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplycenter',
            old_name='owner',
            new_name='controlled_by',
        ),
    ]
