# Generated by Django 2.1.7 on 2019-07-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190728_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedCoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map_abbreviation', models.CharField(max_length=50)),
                ('neighbours', models.ManyToManyField(blank=True, related_name='named_coast_neighbours', to='service.Territory')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_coasts', to='service.Territory')),
            ],
        ),
    ]
