# Generated by Django 2.1.7 on 2019-05-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20190506_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplycenter',
            name='territory',
            field=models.ForeignKey(db_column='territory_id', on_delete=django.db.models.deletion.CASCADE, related_name='supply_center', to='service.Territory', unique=True),
        ),
    ]
