# Generated by Django 2.1.7 on 2019-08-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_namedcoast'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='namedcoast',
            table='named_coast',
        ),
    ]
