# Generated by Django 2.1.7 on 2019-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20190806_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
