# Generated by Django 2.1.7 on 2019-05-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20190506_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplycenter',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplycenter',
            name='territory',
            field=models.OneToOneField(db_column='territory_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='service.Territory'),
        ),
    ]
