# Generated by Django 2.1.7 on 2019-05-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20190506_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplycenter',
            name='territory',
            field=models.OneToOneField(db_column='territory_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supply_center', serialize=False, to='service.Territory'),
        ),
    ]
