# Generated by Django 2.1.7 on 2019-08-06 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20190806_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='named_coast',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.NamedCoast'),
        ),
    ]
