# Generated by Django 2.1.7 on 2019-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_piece_named_coast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedcoast',
            name='map_abbreviation',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
