# Generated by Django 2.1.7 on 2019-08-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20190806_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='named_coast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='service.NamedCoast'),
        ),
    ]
