# Generated by Django 2.1.7 on 2019-08-06 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_command_named_coast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='named_coast',
        ),
        migrations.AddField(
            model_name='command',
            name='source_coast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast'),
        ),
        migrations.AddField(
            model_name='command',
            name='target_coast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='named_coast',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.NamedCoast'),
        ),
    ]
