# Generated by Django 2.1.7 on 2019-05-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20190506_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='challenging',
            field=models.ForeignKey(db_column='challenging_territory_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenging_pieces', to='service.Territory'),
        ),
    ]
