# Generated by Django 2.1.7 on 2019-08-24 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20190806_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='aux_territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aux_commands', to='service.Territory'),
        ),
        migrations.AlterField(
            model_name='command',
            name='source_coast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast'),
        ),
        migrations.AlterField(
            model_name='command',
            name='source_territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_commands', to='service.Territory'),
        ),
        migrations.AlterField(
            model_name='command',
            name='target_coast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast'),
        ),
        migrations.AlterField(
            model_name='command',
            name='target_territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_commands', to='service.Territory'),
        ),
    ]
