# Generated by Django 2.1.7 on 2019-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_piece_challenging'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='current_turn',
            field=models.BooleanField(default=True),
        ),
    ]
