# Generated by Django 2.1.7 on 2019-05-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_turn_current_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='result',
        ),
        migrations.RemoveField(
            model_name='command',
            name='result_display',
        ),
        migrations.AddField(
            model_name='command',
            name='result_message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='successful',
            field=models.BooleanField(default=True),
        ),
    ]
