# Generated by Django 2.1.7 on 2019-08-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20190824_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hold', 'Hold'), ('move', 'Fleet'), ('support', 'Support')], max_length=100)),
                ('valid', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('result_message', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='service.Order')),
                ('source_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_commands', to='service.Territory')),
                ('target_territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_commands', to='service.Territory')),
            ],
            options={
                'db_table': 'move',
            },
        ),
        migrations.RemoveField(
            model_name='command',
            name='aux_territory',
        ),
        migrations.RemoveField(
            model_name='command',
            name='order',
        ),
        migrations.RemoveField(
            model_name='command',
            name='source_coast',
        ),
        migrations.RemoveField(
            model_name='command',
            name='source_territory',
        ),
        migrations.RemoveField(
            model_name='command',
            name='target_coast',
        ),
        migrations.RemoveField(
            model_name='command',
            name='target_territory',
        ),
        migrations.DeleteModel(
            name='Command',
        ),
    ]
