# Generated by Django 2.1.7 on 2019-08-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20190826_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='source_coast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast'),
        ),
        migrations.AddField(
            model_name='move',
            name='target_coast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast'),
        ),
    ]
