# Generated by Django 2.1.7 on 2019-09-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20190901_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('result_message', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Order')),
                ('source_coast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast')),
                ('source_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('result_message', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Order')),
                ('source_coast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast')),
                ('source_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('result_message', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Order')),
                ('source_coast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast')),
                ('source_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('result_message', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Order')),
                ('source_coast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast')),
                ('source_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory')),
                ('target_coast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast')),
                ('target_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory')),
            ],
            options={
                'db_table': 'retreat',
            },
        ),
        migrations.RemoveField(
            model_name='piece',
            name='must_disband',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='must_retreat',
        ),
        migrations.AddField(
            model_name='piece',
            name='dislodged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Piece'),
        ),
    ]
