# Generated by Django 2.1.7 on 2019-09-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_auto_20190901_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_territories', to='service.Nation'),
        ),
    ]
