# Generated by Django 2.1.7 on 2019-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_territory_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='piece_type',
            field=models.CharField(choices=[('army', 'Army'), ('fleet', 'Fleet')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
