# Generated by Django 2.1.7 on 2019-09-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_auto_20190901_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convoy',
            name='source_coast',
        ),
        migrations.RemoveField(
            model_name='disband',
            name='source_coast',
        ),
        migrations.RemoveField(
            model_name='hold',
            name='source_coast',
        ),
        migrations.RemoveField(
            model_name='move',
            name='source_coast',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='source_coast',
        ),
        migrations.RemoveField(
            model_name='support',
            name='source_coast',
        ),
        migrations.RemoveField(
            model_name='support',
            name='target_territory',
        ),
    ]
