# Generated by Django 2.1.7 on 2019-09-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20190901_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convoy',
            name='target_territory',
        ),
        migrations.RemoveField(
            model_name='move',
            name='target_territory',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='target_territory',
        ),
        migrations.AddField(
            model_name='support',
            name='target_territory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory'),
            preserve_default=False,
        ),
    ]
