# Generated by Django 2.1.7 on 2019-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_retreat_target_territory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='territory',
        ),
        migrations.AddField(
            model_name='build',
            name='state',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('succeeds', 'succeeds'), ('fails', 'fails')], default='unresolved', max_length=15),
        ),
        migrations.AddField(
            model_name='convoy',
            name='state',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('succeeds', 'succeeds'), ('fails', 'fails')], default='unresolved', max_length=15),
        ),
        migrations.AddField(
            model_name='disband',
            name='state',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('succeeds', 'succeeds'), ('fails', 'fails')], default='unresolved', max_length=15),
        ),
        migrations.AddField(
            model_name='hold',
            name='state',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('succeeds', 'succeeds'), ('fails', 'fails')], default='unresolved', max_length=15),
        ),
        migrations.AddField(
            model_name='move',
            name='state',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('succeeds', 'succeeds'), ('fails', 'fails')], default='unresolved', max_length=15),
        ),
        migrations.AddField(
            model_name='retreat',
            name='state',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('succeeds', 'succeeds'), ('fails', 'fails')], default='unresolved', max_length=15),
        ),
        migrations.AddField(
            model_name='support',
            name='state',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('succeeds', 'succeeds'), ('fails', 'fails')], default='unresolved', max_length=15),
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
