# Generated by Django 2.1.7 on 2019-09-14 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_auto_20190911_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hold', 'Hold'), ('move', 'Move'), ('support', 'Support'), ('convoy', 'Convoy'), ('retreat', 'Retreat'), ('build', 'Build'), ('disband', 'Disband')], default='hold', max_length=8)),
                ('state', models.CharField(choices=[('unresolved', 'Unresolved'), ('succeeds', 'Succeeds'), ('fails', 'Fails')], default='unresolved', max_length=15)),
                ('valid', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('result_message', models.CharField(blank=True, max_length=100, null=True)),
                ('aux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Order')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory')),
                ('target_coast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.NamedCoast')),
            ],
            options={
                'db_table': 'command',
            },
        ),
        migrations.RemoveField(
            model_name='build',
            name='order',
        ),
        migrations.RemoveField(
            model_name='build',
            name='source_coast',
        ),
        migrations.RemoveField(
            model_name='build',
            name='source_territory',
        ),
        migrations.RemoveField(
            model_name='convoy',
            name='aux_territory',
        ),
        migrations.RemoveField(
            model_name='convoy',
            name='order',
        ),
        migrations.RemoveField(
            model_name='convoy',
            name='source_territory',
        ),
        migrations.RemoveField(
            model_name='convoy',
            name='target_territory',
        ),
        migrations.RemoveField(
            model_name='disband',
            name='order',
        ),
        migrations.RemoveField(
            model_name='disband',
            name='source_territory',
        ),
        migrations.RemoveField(
            model_name='hold',
            name='order',
        ),
        migrations.RemoveField(
            model_name='hold',
            name='source_territory',
        ),
        migrations.RemoveField(
            model_name='move',
            name='order',
        ),
        migrations.RemoveField(
            model_name='move',
            name='source_territory',
        ),
        migrations.RemoveField(
            model_name='move',
            name='target_coast',
        ),
        migrations.RemoveField(
            model_name='move',
            name='target_territory',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='order',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='source_territory',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='target_coast',
        ),
        migrations.RemoveField(
            model_name='retreat',
            name='target_territory',
        ),
        migrations.RemoveField(
            model_name='support',
            name='aux_territory',
        ),
        migrations.RemoveField(
            model_name='support',
            name='order',
        ),
        migrations.RemoveField(
            model_name='support',
            name='source_territory',
        ),
        migrations.RemoveField(
            model_name='support',
            name='target_territory',
        ),
        migrations.DeleteModel(
            name='Build',
        ),
        migrations.DeleteModel(
            name='Convoy',
        ),
        migrations.DeleteModel(
            name='Disband',
        ),
        migrations.DeleteModel(
            name='Hold',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.DeleteModel(
            name='Retreat',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
