# Generated by Django 2.1.7 on 2019-09-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_auto_20190914_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='piece',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Piece'),
        ),
    ]
