# Generated by Django 2.1.7 on 2019-09-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_command_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='aux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory'),
        ),
        migrations.AlterField(
            model_name='command',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory'),
        ),
    ]
