# Generated by Django 2.1.7 on 2019-09-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_auto_20190915_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='aux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory'),
        ),
        migrations.AlterField(
            model_name='command',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='service.Territory'),
        ),
    ]
