data = [
    {'model': 'core.territory', 'pk': 1,
     'fields': {'name': 'adriatic sea', 'neighbours': [20, 22, 11, 53, 56],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}
     },
    {'model': 'core.territory', 'pk': 2,
     'fields': {'name': 'aegean sea', 'neighbours': [5, 73, 28, 7, 33, 11, 50],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}
     },
    {'model': 'core.territory', 'pk': 3,
     'fields': {'name': 'baltic sea', 'neighbours': [24, 6, 29, 35, 48, 51],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}
     },
    {'model': 'core.territory', 'pk': 4,
     'fields': {'name': 'barrents sea', 'neighbours': [15, 42, 75],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 5,
     'fields': {'name': 'black sea', 'neighbours': [21, 23, 73, 28, 47, 49],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 6,
     'fields': {'name': 'gulf of bothnia',
                'neighbours': [3, 31, 37, 51, 75, 75],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 7,
     'fields': {'name': 'eastern mediterranean', 'neighbours': [2, 50, 52],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 8, 'fields': {'name': 'english channel',
                                                    'neighbours': [25, 26, 12,
                                                                   36,
                                                                   13, 16, 43,
                                                                   57],
                                                    'shared_coasts': [],
                                                    'coastal': False,
                                                    'controlled_by_initial': None,
                                                    'type': 'sea'}},
    {'model': 'core.territory', 'pk': 9,
     'fields': {'name': 'gulf of lyon', 'neighbours': [39, 44, 74, 55, 18, 19],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 10,
     'fields': {'name': 'helgoland bight', 'neighbours': [29, 34, 35, 16],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 11, 'fields': {'name': 'ionian sea',
                                                     'neighbours': [2, 1, 20,
                                                                    22,
                                                                    33, 41, 54,
                                                                    18],
                                                     'shared_coasts': [],
                                                     'coastal': False,
                                                     'controlled_by_initial': None,
                                                     'type': 'sea'}},
    {'model': 'core.territory', 'pk': 12,
     'fields': {'name': 'irish sea', 'neighbours': [8, 38, 13, 14, 57],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 13, 'fields': {'name': 'mid atlantic',
                                                     'neighbours': [26, 8, 32,
                                                                    12,
                                                                    40, 14, 74,
                                                                    45, 19],
                                                     'shared_coasts': [],
                                                     'coastal': False,
                                                     'controlled_by_initial': None,
                                                     'type': 'sea'}},
    {'model': 'core.territory', 'pk': 14,
     'fields': {'name': 'north atlantic', 'neighbours': [27, 12, 38, 13, 15],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 15,
     'fields': {'name': 'norwegian sea', 'neighbours': [4, 27, 30, 14, 42, 16],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 16, 'fields': {'name': 'north sea',
                                                     'neighbours': [25, 29, 30,
                                                                    8,
                                                                    10, 34, 36,
                                                                    15, 42, 17,
                                                                    58],
                                                     'shared_coasts': [],
                                                     'coastal': False,
                                                     'controlled_by_initial': None,
                                                     'type': 'sea'}},
    {'model': 'core.territory', 'pk': 17,
     'fields': {'name': 'skagerrak', 'neighbours': [29, 16, 42, 51],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': None, 'type': 'sea'}},
    {'model': 'core.territory', 'pk': 18, 'fields': {'name': 'tyrrhenian sea',
                                                     'neighbours': [9, 11, 41,
                                                                    46,
                                                                    54, 55,
                                                                    19],
                                                     'shared_coasts': [],
                                                     'coastal': False,
                                                     'controlled_by_initial': None,
                                                     'type': 'sea'}},
    {'model': 'core.territory', 'pk': 19,
     'fields': {'name': 'western mediterranean',
                'neighbours': [9, 13, 40, 74, 54, 18], 'shared_coasts': [],
                'coastal': False, 'controlled_by_initial': None,
                'type': 'sea'}},
    {'model': 'core.territory', 'pk': 20,
     'fields': {'name': 'albania', 'neighbours': [1, 33, 11, 67, 53],
                'shared_coasts': [33, 53], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 21,
     'fields': {'name': 'ankara', 'neighbours': [23, 5, 28, 50],
                'shared_coasts': [23, 28], 'coastal': True,
                'controlled_by_initial': 7, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 22,
     'fields': {'name': 'apulia', 'neighbours': [1, 11, 41, 46, 56],
                'shared_coasts': [41, 56], 'coastal': True,
                'controlled_by_initial': 5, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 23,
     'fields': {'name': 'armenia', 'neighbours': [21, 21, 49, 50, 52],
                'shared_coasts': [49, 21], 'coastal': True,
                'controlled_by_initial': 7, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 24,
     'fields': {'name': 'berlin', 'neighbours': [3, 35, 64, 48, 68],
                'shared_coasts': [35, 48], 'coastal': True,
                'controlled_by_initial': 3, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 25,
     'fields': {'name': 'belgium', 'neighbours': [61, 8, 34, 43, 66, 16],
                'shared_coasts': [34, 43], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 26,
     'fields': {'name': 'brest', 'neighbours': [8, 32, 13, 65, 43],
                'shared_coasts': [32, 43], 'coastal': True,
                'controlled_by_initial': 2, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 27,
     'fields': {'name': 'clyde', 'neighbours': [30, 38, 12, 14, 15],
                'shared_coasts': [30, 38], 'coastal': True,
                'controlled_by_initial': 1, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 28,
     'fields': {'name': 'constantinople', 'neighbours': [2, 21, 5, 73, 50],
                'shared_coasts': [21, 50], 'coastal': True,
                'controlled_by_initial': 7, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 29,
     'fields': {'name': 'denmark', 'neighbours': [3, 10, 35, 16, 17, 51],
                'shared_coasts': [35, 51], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 30,
     'fields': {'name': 'edinburgh', 'neighbours': [27, 38, 15, 16, 58],
                'shared_coasts': [27, 58], 'coastal': True,
                'controlled_by_initial': 1, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 31,
     'fields': {'name': 'finland', 'neighbours': [6, 42, 75, 51],
                'shared_coasts': [51], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 32,
     'fields': {'name': 'gascony', 'neighbours': [26, 61, 39, 13, 65, 74],
                'shared_coasts': [26], 'coastal': True,
                'controlled_by_initial': 2, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 33,
     'fields': {'name': 'greece', 'neighbours': [2, 20, 73, 11, 67],
                'shared_coasts': [20, 73], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 34,
     'fields': {'name': 'holland', 'neighbours': [25, 10, 35, 16, 66],
                'shared_coasts': [25, 35], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 35,
     'fields': {'name': 'kiel', 'neighbours': [3, 24, 29, 10, 34, 64, 66],
                'shared_coasts': [24, 29, 34], 'coastal': True,
                'controlled_by_initial': 3, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 36,
     'fields': {'name': 'london', 'neighbours': [8, 16, 57, 58],
                'shared_coasts': [57, 58], 'coastal': True,
                'controlled_by_initial': 1, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 37,
     'fields': {'name': 'livonia', 'neighbours': [3, 6, 63, 48, 75, 72],
                'shared_coasts': [48], 'coastal': True,
                'controlled_by_initial': 6, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 38,
     'fields': {'name': 'liverpool', 'neighbours': [27, 30, 12, 14, 57, 58],
                'shared_coasts': [27, 57], 'coastal': True,
                'controlled_by_initial': 1, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 39,
     'fields': {'name': 'marseilles', 'neighbours': [61, 32, 9, 44, 74],
                'shared_coasts': [44], 'coastal': True,
                'controlled_by_initial': 2, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 40,
     'fields': {'name': 'north africa', 'neighbours': [13, 54, 19],
                'shared_coasts': [54], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 41,
     'fields': {'name': 'naples', 'neighbours': [22, 11, 46, 18],
                'shared_coasts': [22, 46], 'coastal': True,
                'controlled_by_initial': 5, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 42,
     'fields': {'name': 'norway', 'neighbours': [4, 31, 15, 16, 17, 75, 51],
                'shared_coasts': [51], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 43,
     'fields': {'name': 'picardy', 'neighbours': [26, 25, 61, 8, 65],
                'shared_coasts': [26, 25], 'coastal': True,
                'controlled_by_initial': 2, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 44,
     'fields': {'name': 'piedmont', 'neighbours': [9, 39, 55, 69, 56],
                'shared_coasts': [39, 55], 'coastal': True,
                'controlled_by_initial': 5, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 45,
     'fields': {'name': 'portugal', 'neighbours': [13, 74],
                'shared_coasts': [],
                'coastal': True, 'controlled_by_initial': None,
                'type': 'land'}},
    {'model': 'core.territory', 'pk': 46,
     'fields': {'name': 'rome', 'neighbours': [22, 41, 55, 18, 56],
                'shared_coasts': [41, 55], 'coastal': True,
                'controlled_by_initial': 5, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 47,
     'fields': {'name': 'rumania', 'neighbours': [5, 60, 73, 62, 67, 49, 70],
                'shared_coasts': [49], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 48,
     'fields': {'name': 'prussia', 'neighbours': [3, 24, 37, 68, 72],
                'shared_coasts': [24, 37], 'coastal': True,
                'controlled_by_initial': 3, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 49,
     'fields': {'name': 'sevastapol', 'neighbours': [23, 5, 63, 47, 70],
                'shared_coasts': [23, 47], 'coastal': True,
                'controlled_by_initial': 6, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 50,
     'fields': {'name': 'smyrna', 'neighbours': [2, 23, 21, 28, 7, 52],
                'shared_coasts': [28, 52], 'coastal': True,
                'controlled_by_initial': 7, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 51,
     'fields': {'name': 'sweden', 'neighbours': [3, 6, 29, 31, 42, 17],
                'shared_coasts': [29, 31, 42], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 52,
     'fields': {'name': 'syria', 'neighbours': [23, 7, 50],
                'shared_coasts': [50],
                'coastal': True, 'controlled_by_initial': 7, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 53,
     'fields': {'name': 'trieste', 'neighbours': [1, 20, 60, 52, 69, 56, 71],
                'shared_coasts': [20, 56], 'coastal': True,
                'controlled_by_initial': 4, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 54,
     'fields': {'name': 'tunis', 'neighbours': [11, 40, 18, 19],
                'shared_coasts': [40], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 55,
     'fields': {'name': 'tuscany', 'neighbours': [9, 44, 46, 18, 56],
                'shared_coasts': [44, 46], 'coastal': True,
                'controlled_by_initial': 5, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 56,
     'fields': {'name': 'venice', 'neighbours': [1, 22, 46, 44, 53, 18, 69],
                'shared_coasts': [22, 53], 'coastal': True,
                'controlled_by_initial': 5, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 57,
     'fields': {'name': 'wales', 'neighbours': [8, 12, 36, 38, 58],
                'shared_coasts': [36, 38], 'coastal': True,
                'controlled_by_initial': 1, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 58,
     'fields': {'name': 'yorkshire', 'neighbours': [30, 36, 38, 16, 57],
                'shared_coasts': [30, 36], 'coastal': True,
                'controlled_by_initial': 1, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 59,
     'fields': {'name': 'bohemia', 'neighbours': [62, 64, 68, 69, 71],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': 4,
                'type': 'land'}}, {'model': 'core.territory', 'pk': 60,
                                   'fields': {'name': 'budapest',
                                              'neighbours': [62, 47, 67, 53,
                                                             71],
                                              'shared_coasts': [],
                                              'coastal': False,
                                              'controlled_by_initial': 4,
                                              'type': 'land'}},
    {'model': 'core.territory', 'pk': 61, 'fields': {'name': 'burgundy',
                                                     'neighbours': [26, 25, 32,
                                                                    39, 64, 65,
                                                                    43, 66],
                                                     'shared_coasts': [],
                                                     'coastal': False,
                                                     'controlled_by_initial': 2,
                                                     'type': 'land'}},
    {'model': 'core.territory', 'pk': 62,
     'fields': {'name': 'galicia', 'neighbours': [59, 60, 47, 68, 70, 71, 72],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': 4,
                'type': 'land'}}, {'model': 'core.territory', 'pk': 63,
                                   'fields': {'name': 'moscow',
                                              'neighbours': [37, 47, 49, 75,
                                                             70,
                                                             72],
                                              'shared_coasts': [],
                                              'coastal': False,
                                              'controlled_by_initial': 6,
                                              'type': 'land'}},
    {'model': 'core.territory', 'pk': 64,
     'fields': {'name': 'munich', 'neighbours': [24, 59, 61, 35, 68, 66, 69],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': 3,
                'type': 'land'}}, {'model': 'core.territory', 'pk': 65,
                                   'fields': {'name': 'paris',
                                              'neighbours': [26, 61, 32, 43,
                                                             68,
                                                             66, 69],
                                              'shared_coasts': [],
                                              'coastal': False,
                                              'controlled_by_initial': 2,
                                              'type': 'land'}},
    {'model': 'core.territory', 'pk': 66,
     'fields': {'name': 'ruhr', 'neighbours': [26, 61, 34, 35, 64],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': 3,
                'type': 'land'}}, {'model': 'core.territory', 'pk': 67,
                                   'fields': {'name': 'serbia',
                                              'neighbours': [20, 60, 73, 33,
                                                             47,
                                                             53],
                                              'shared_coasts': [],
                                              'coastal': False,
                                              'controlled_by_initial': None,
                                              'type': 'land'}},
    {'model': 'core.territory', 'pk': 68,
     'fields': {'name': 'silesia', 'neighbours': [24, 59, 62, 64, 48, 72],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': 3,
                'type': 'land'}}, {'model': 'core.territory', 'pk': 69,
                                   'fields': {'name': 'tyrolia',
                                              'neighbours': [59, 64, 53, 56,
                                                             71],
                                              'shared_coasts': [],
                                              'coastal': False,
                                              'controlled_by_initial': 4,
                                              'type': 'land'}},
    {'model': 'core.territory', 'pk': 70,
     'fields': {'name': 'ukraine', 'neighbours': [62, 63, 47, 49, 72],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': 6,
                'type': 'land'}}, {'model': 'core.territory', 'pk': 71,
                                   'fields': {'name': 'vienna',
                                              'neighbours': [59, 60, 62, 53,
                                                             69],
                                              'shared_coasts': [],
                                              'coastal': False,
                                              'controlled_by_initial': 4,
                                              'type': 'land'}},
    {'model': 'core.territory', 'pk': 72,
     'fields': {'name': 'warsaw', 'neighbours': [62, 37, 63, 68, 48, 70],
                'shared_coasts': [], 'coastal': False,
                'controlled_by_initial': 6,
                'type': 'land'}}, {'model': 'core.territory', 'pk': 73,
                                   'fields': {'name': 'bulgaria',
                                              'neighbours': [2, 5, 28, 33, 47,
                                                             67],
                                              'shared_coasts': [47, 33, 28],
                                              'coastal': True,
                                              'controlled_by_initial': None,
                                              'type': 'land'}},
    {'model': 'core.territory', 'pk': 74,
     'fields': {'name': 'spain', 'neighbours': [32, 39, 45, 9, 19, 13],
                'shared_coasts': [13, 32, 45, 39, 9], 'coastal': True,
                'controlled_by_initial': None, 'type': 'land'}},
    {'model': 'core.territory', 'pk': 75,
     'fields': {'name': 'st. petersburg', 'neighbours': [31, 37, 63, 42],
                'shared_coasts': [37, 31, 42], 'coastal': True,
                'controlled_by_initial': 6, 'type': 'land'}}]
